apiVersion: v1
kind: Service
metadata:
  name: demoxxx1-svc
spec:
  ports:
  - name: http
    port: 9080
  selector:
    app: demoxxx1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoxxx1-v1
spec:
  template:
      labels:
        app: demoxxx1
        version: v1
    spec:
      containers:
      - image: demoxxx1-v1:latest
        name: demoxxx1
        resources: {}
