apiVersion: v1
kind: Service
metadata:
  name: demoxxx1-svc
spec:
  ports:
  - name: http
    port: 9080
  selector:
    app: demoxxx1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoxxx-v1
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "demoxxx-selector"
        version: "v1"
    spec:
      containers:
      - name: demoxxx
        image: demoxxx1-v1:latest
        readinessProbe:
          httpGet:
            path: /demoxxx/health
            port: 9080
          initialDelaySeconds: 20
